version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: indian-numismatics
    path: dictionaries/indian-numismatics.txt
  - name: chinese-numismatics
    path: dictionaries/chinese-numismatics.txt
dictionaries:
  - en_US
  - en_GB
  # You may need `npm install --global @cspell/dict-ar` for the Arabic dictionary
  - ar
  - indian-numismatics
  - chinese-numismatics
words: []
ignoreWords: []
import: []
